### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by dmitriy-sokolyanskiy** [dmitriy-sokolyanskiy/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by dasha-korotkykh** [comment]
Хей, привіт! Якщо ти складаєш резюме про себе чи улюбленого персонажа/людину, тобі потрібно написати цей контент самій, я буду рада його продивитися і порадити щось, якщо буде потрібно. Якщо ти складаєш сторінку на замовлення Рю або Дональда, тобі потрібно взяти інформацію з їхніх файлів відповідно, які вказані в описі завдання. Знаєш де лінки на ті файли, чи скинути тобі? :)
P.S. те саме стосується і інших issues

**Comment by dmitriy-sokolyanskiy** [comment]
Hi! First of all, thanks a lot for your attention. I really appreciate it. I'm creating a resume about myself.
I've seen the Donald Trump's and Ryu's file link

**Comment by dmitriy-sokolyanskiy** [comment]
Could you tell :
1. Does It only needs markup without styles?
2. What flow do I need to use?  
all 4 commits on develop branch or  commit -> master -> break away from the master branch  -> commit -> master .....

**Comment by dasha-korotkykh** [comment]
1. According to lesson you are linking Volodymyr's stylesheet, that takes care of your CSS styles, so you don't need markup, but you should include text in html tags (headings, divs, lists, etc). 
2. With small updates or commits with common purpose (create the page content, for example), you can put all four of them in one pull request to master branch. If in future you would be working on significant changes or they would refer to different functionality, you should do a separate pull request for each so it would be easier for you to revert if needed.

**Comment by dmitriy-sokolyanskiy** [comment]
<div class="additional">
    <section>
        <h3>Languages</h3>
        <p class="tags small">
            <span>УКРАЇНСЬКА</span></a>
            <span>РУССКИЙ</span></a>
            <span>ENGLISH</span>
        </p>
    </section>
    <section>
        <h3>Skills</h3>
        <p class="tags small">
            HTML
            CSS
            JS
            BOOTSTRAP
            LESS
            SASS
            JQUERY
            REACT
            REDUX
            LODASH
            GRUNT
            GULP
            BOWER
            WEBPACK
            NODEJS
            NPM
            PHOTOSHOP
            LINUX
            WINDOWS
            MYSQL
            POSTGRESQL
            MICROSOFT S
            QL
        </p>
    </section>
    <section>
        <h3>Character</h3>
        <p class="tags small">
            EXPLORER
            STRAIGHTFORWARD
            DEBATER
            DEVOTED
            PEDANTIC
            CONFIDENT
            CONSISTENT
            CHALLENGING
        </p>
    </section>
    <section>
        <h3>Likes😃</h3>
        <p class="tags small">
            BICYCLE RIDING
            RUNNING
            HUMOUR
            PATIENCE
            MOVIES
            GAMES
            DEMOCRACY
        </p>
    </section>
    <section>
        <h3>Dislikes😞</h3>
        <p class="tags small">
            OWN BAD HABITS
            POLITICS
            RACISM
            INCOMPETENCE
        </p>
    </section>
    <section>
        <h3>Wants🥺</h3>
        <p class="tags small bulleted">
            TO READ MORE
            BLIND TYPING IN ENGLISH
            OBSERVE & LISTENBE
            TO BE FIT AND HEALTHY
            DO A LOT OF USEFUL THINGS
        </p>
    </section>
</div>
